### ISSUE TITLE
LEDs are offset

### ISSUE THREAD

**Issue by karai17** [djpohly/piuio#13]
Last night I refreshed my arcade pc with Fedora 25. After fully upgrading to latest kernel (4.9.10) and other things, I installed StepMania from master branch (5.2 WIP) and compiled this driver. When I set `LightsDriver=PIUIO_Leds` the LEDs are seemingly offset. Pressing `DOWN` makes the `RIGHT` LED glow, etc. I didn't touch any of my hardware. I was using an upgraded Fedora 25 on kernel 4.9.9 with this PIUIO driver and StepMania 5.0.9 previously and it all worked fine.

Any thoughts?

**Comment by karai17** [comment]
I just built 5.0.12 and it seems to be working there. Maybe @shakesoda can think of a reason why this is happening?

**Comment by kyzentun** [comment]
LightsDriver PIUIO LEDs 5.0.x history: https://github.com/stepmania/stepmania/commits/5_0/src/arch/Lights/LightsDriver_Linux_PIUIO_Leds.cpp

5.2 WNIP history: https://github.com/stepmania/stepmania/commits/master/src/arch/Lights/LightsDriver_Linux_PIUIO_Leds.cpp

My libmmmagic commit touched the file because all the LightsDriver classes were using "REGISTER_SOUND_DRIVER" instead of "REGISTER_LIGHTS_DRIVER" (thanks, whoever copy pasted that to a dozen source files without fixing it.  This is why I immediately yell at anyone who uses copy paste everywhere)

So whatever caused the problem is probably not in LightsDriver PIUIO LEDs.

Use ```git checkout <hash>``` where "<hash>" means the hash from a history listing and try the commits that happened in the Lights directory.  (Lights history to get hashes from: https://github.com/stepmania/stepmania/commits/master/src/arch/Lights)

Narrow down one commit where it doesn't happen and it does for the next, and you'll know what commit caused the problem.  If the problem commit was in Lights and not some other part of the engine.

**Comment by karai17** [comment]
Thanks for the info. Can you please pop on IRC tomorrow and help me sort this? <3

**Comment by karai17** [comment]
Those commits look like they are long before 5.0.12 was released. 5.0.12 seems to work fine so it probably isn't something in that file... But I can take a look tomorrow for sure.

**Comment by kyzentun** [comment]
This commit is the cause: https://github.com/stepmania/stepmania/commit/52aebc026c11cbc58e7a675a5f5b8ced6f78f37b

If GAME_BUTTON_SCREENSHOT is moved to after GAME_BUTTON_CUSTOM_19 in the enum, the lights will probably not be offset.

**Comment by karai17** [comment]
Ah! that looks plausible!

**Comment by kyzentun** [comment]
The lights drivers make the reasonable assumption of one light per game button in their data structures: https://github.com/stepmania/stepmania/blob/master/src/arch/Lights/LightsDriver_Linux_PIUIO_Leds.cpp#L32

I don't know if you have enough game buttons to get the "Error setting button light <button>" warning in the log file, but that would be confirmation.

Anyway, move the values in the GameButton enum around, compile and make sure you can play and remap the screenshot key and stuff.  I haven't thought of a good solution for how lights and game buttons are mapped, so the enum will just have to look misorganized.

**Comment by karai17** [comment]
Reverting that commit locally fixed the issue.
